# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliadorEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Avaliador')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.EventoCientifico')),
            ],
        ),
    ]
